version: "3.9"
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - "8081:8081"
  timetracker:
    image: "alirizasaral/timetracker:1"
    ports:
      - "8080:8080"